param(
    [Parameter(Mandatory=$true)][string]$Name,
    [string]$Domain = '',
    [string]$ContactEmail = '',
    [switch]$InitGit
)

function SafeName($n){ return ($n -replace '[^a-zA-Z0-9\-_. ]','') -replace ' ','_' }

$project = SafeName($Name)
$root = Join-Path -Path (Split-Path -Parent $MyInvocation.MyCommand.Definition) -ChildPath ".."
$sitesDir = Join-Path -Path $root -ChildPath "WEBSITES"
if(-not (Test-Path $sitesDir)){ New-Item -Path $sitesDir -ItemType Directory | Out-Null }

$target = Join-Path -Path $sitesDir -ChildPath $project
if(Test-Path $target){ Write-Error "Target path already exists: $target"; exit 1 }

New-Item -Path $target -ItemType Directory | Out-Null
New-Item -Path (Join-Path $target 'assets') -ItemType Directory | Out-Null

# INDEX.HTML
$index = @"
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>$Name</title>
    <link rel="stylesheet" href="STYLE.CSS" />
  </head>
  <body>
    <header>
      <h1>$Name</h1>
      <p>Project generated by scaffold_website.ps1</p>
    </header>
    <main>
      <p>Welcome to $Name. Replace this content with your site.</p>
    </main>
    <footer>
      <p>Contact: $ContactEmail</p>
    </footer>
    <script src="SCRIPT.JS"></script>
  </body>
</html>
"@

$css = @"
/* Basic stylesheet generated by scaffold_website.ps1 */
body{font-family:system-ui,Segoe UI,Arial;margin:0;padding:24px;background:#f7f9fc;color:#07203a}
header h1{margin:0}
"@

$js = @"
// Basic script placeholder
document.addEventListener('DOMContentLoaded',()=>console.log('Welcome to $Name'))
"@

Set-Content -Path (Join-Path $target 'INDEX.HTML') -Value $index -Encoding UTF8
Set-Content -Path (Join-Path $target 'STYLE.CSS') -Value $css -Encoding UTF8
Set-Content -Path (Join-Path $target 'SCRIPT.JS') -Value $js -Encoding UTF8

if($Domain -ne ''){
    Set-Content -Path (Join-Path $target 'CNAME') -Value $Domain -Encoding UTF8
    Set-Content -Path (Join-Path $target 'DOMAIN_NOTE.txt') -Value "Domain: $Domain`nRegister this domain via a registrar and point DNS to your host." -Encoding UTF8
}

Set-Content -Path (Join-Path $target 'README.md') -Value "# $Name`nThis site was created by scaffold_website.ps1.`n`nStructure:`n- INDEX.HTML`n- STYLE.CSS`n- SCRIPT.JS`n- assets/`n" -Encoding UTF8

Set-Content -Path (Join-Path $target 'README_DEPLOY.md') -Value "See README_DEPLOY.md in project root or use simple static hosting (GitHub Pages, Netlify, Vercel)." -Encoding UTF8

if($ContactEmail -ne ''){
  Add-Content -Path (Join-Path $target 'README.md') -Value "`nContact: $ContactEmail"
}

if($InitGit){
  try{
    Push-Location $target
    git init | Out-Null
    git add . | Out-Null
    git commit -m "Initial scaffold for $Name" | Out-Null
    Pop-Location
  } catch { Write-Warning "Git init failed or git not available." }
}

Write-Output "Project created: $target"
Write-Output "Open INDEX.HTML inside the new folder to preview."
